# Generated by Django 5.2 on 2025-05-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1234567890, max_length=100),
            preserve_default=False,
        ),
    ]
