# Generated by Django 5.2 on 2025-05-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('vacunacion', 'Vacunación'), ('desparasitacion', 'Desparasitación'), ('visita', 'Visita al veterinario')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
